apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-boilerplate
  namespace: APP_NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-boilerplate
  template:
    metadata:
      labels:
        app: go-boilerplate
        version: APP_VERSION
    spec:
      containers:
        - name: go-boilerplate
          image: APP_IMAGE
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 6
            periodSeconds: 4
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 8
            periodSeconds: 4
            failureThreshold: 4
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 2Gi
          env:
            - name: ENV
              value: production
